/**
 * Wire protocol shared between the Node bridge and the Studio plugin.
 *
 * Transport is deliberately dumb: the server pushes `Command` frames down an
 * SSE stream (or hands them out via long-poll when SSE is unavailable) and the
 * plugin POSTs a matching `CommandResult` back to /result. Every frame is
 * correlated by `id`, so both transports behave identically from the tool side.
 */

/** A single request from the MCP server to one Studio instance. */
export interface Command {
  id: string;
  /** Handler name the plugin dispatches on, e.g. "inspect" or "script.edit". */
  op: string;
  params: Record<string, unknown>;
}

/** Structured failure returned by the plugin. `hint` is surfaced to the agent. */
export interface CommandError {
  code: string;
  message: string;
  hint?: string;
}

export interface CommandResult {
  id: string;
  ok: boolean;
  data?: unknown;
  error?: CommandError;
}

/**
 * What one MCP client says about itself, and what the console shows.
 *
 * The name comes from the MCP handshake, so it is whatever the agent calls
 * itself -- "claude-code", "codex", "cursor" -- rather than anything this
 * server guesses. Unknown is a real answer: a client that skipped the field is
 * still connected, and saying so beats inventing a label for it.
 */
export interface ClientView {
  name: string;
  version: string;
  pid: number;
  connectedAt: number;
  /**
   * True for an agent the console panel started itself.
   *
   * Such a client is not news. The panel asked for it, printed the request, and
   * is printing its every step -- so announcing its arrival and departure as
   * though a stranger had joined the bridge says nothing the reader does not
   * already know, three times per prompt. Counted separately for that reason
   * alone; in every other respect it is an ordinary client.
   */
  spawned?: boolean;
}

/** Identity a plugin declares when it opens its stream. */
export interface StudioIdentity {
  /** Stable per-Studio-process id generated by the plugin. */
  studioId: string;
  placeName: string;
  placeId: number;
  /** Plugin version, used to warn on protocol drift. */
  pluginVersion: string;
  /** Fingerprint of the Luau sources the plugin was built from. */
  buildId: string;
  /**
   * The plugin's own PROTOCOL_VERSION, compared against this server's.
   *
   * Defaults to 1 when absent (a plugin built before this field existed),
   * which is also the only value PROTOCOL_VERSION has ever had — so an old
   * plugin talking to an old server reads as a match, not a warning.
   */
  protocolVersion: number;
  /** "sse" when the plugin holds a live stream, "poll" for the fallback. */
  transport: "sse" | "poll";
  /**
   * Which of Studio's sessions this is — "edit", "playtest server" and so on.
   *
   * Not announced at connect, because a plugin cannot know it before the
   * DataModel settles. Filled in by the first call that reads status and cached
   * afterwards, so choosing between two identically-named sessions does not
   * need a round trip — notably inside the AMBIGUOUS_STUDIO error, where making
   * one is not an option.
   */
  context?: string;
}

export interface StudioSession extends StudioIdentity {
  connectedAt: number;
  lastSeenAt: number;
}

/**
 * Bumped whenever `Command`/`CommandResult` shapes change incompatibly. The
 * plugin sends its own value at handshake so we can tell the user to update
 * rather than failing with a confusing schema error later.
 */
export const PROTOCOL_VERSION = 1;

/**
 * Human-readable warning when a connected plugin's wire protocol does not
 * match this server's, or null when it matches.
 *
 * Mirrors `pluginStalenessWarning` (buildId) rather than replacing it: buildId
 * catches a plugin still running older *behaviour*, this catches the wire
 * *shape* changing under it. The header this rides on has always been sent —
 * PROTOCOL_VERSION has just never moved, so this has never had anything to
 * report. It exists so the day it does move, the plugin says so instead of
 * failing in whatever way a shape mismatch happens to fail.
 */
export function protocolMismatchWarning(reported: number): string | null {
  if (reported === PROTOCOL_VERSION) return null;
  return reported < PROTOCOL_VERSION
    ? `The connected Studio plugin speaks an older wire protocol (v${reported}) than ` +
        `this server (v${PROTOCOL_VERSION}). Run \`npx -y @el4cteo/rbx-studio-mcp --install-plugin\`, ` +
        `then quit Studio completely and start it again — focusing the window does not ` +
        `reload a plugin.`
    : `The connected Studio plugin speaks a newer wire protocol (v${reported}) than ` +
        `this server (v${PROTOCOL_VERSION}) understands. Update the server: reinstall ` +
        `with \`npx -y @el4cteo/rbx-studio-mcp\` (npx always fetches the latest).`;
}

/**
 * Custom header every plugin request must carry. Browsers cannot set it on a
 * cross-origin request without a preflight the bridge never answers, which is
 * what stops a malicious web page from driving the user's Studio via DNS
 * rebinding. Cheaper and less fragile than a token the user has to copy.
 */
export const CLIENT_HEADER = "x-roblox-studio-mcp";
